###################################################################

# Created by write_sdc on Tue Nov  9 23:06:31 2021

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {DOUT0[12]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[11]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT0[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[12]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[11]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT1[0]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[12]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[11]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[10]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[9]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[8]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[7]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[6]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[5]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[4]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[3]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[2]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[1]}]
set_load -pin_load 3.40189 [get_ports {DOUT2[0]}]
set_load -pin_load 3.40189 [get_ports VOUT]
create_clock [get_ports CLK]  -name MY_CLK  -period 7.2  -waveform {0 3.6}
set_input_delay -clock MY_CLK  -max 0.5  [get_ports RST_N]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN0[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {DIN2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports VIN]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H0[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H1[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H2[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H3[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H4[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H5[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H6[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H7[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H8[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H9[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {H10[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT0[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT1[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {DOUT2[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports VOUT]
